name: Build & Push Container (GHCR)

on:
  push:
    paths:
      - 'container/**'
      - '.github/workflows/docker-image.yml'
    branches: [ main ]

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: ./container
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/wine-quality-sagemaker:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
